apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cadvisor
  endpoints:
    - port: "http-metrics"  # 👈 correspond au nom du port dans le Service
      interval: 15s
