apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: express-monitor
  labels:
    release: prometheus  # Doit correspondre au label du Prometheus Operator
spec:
  selector:
    matchLabels:
      app: backend  # Doit correspondre au label du Service express-service
  namespaceSelector:
    matchNames:
      - default  # ou le namespace réel du service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
