# k8s/front-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30002
  type: NodePort