apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: seynabou02/react-frontend:latest
        ports:
        - containerPort: 80    # Nginx écoute sur le port 80
        env:
        - name: REACT_APP_API_URL
          value: "http://192.168.49.2:30001/api"