apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: jenkins
  endpoints:
    - port: http
      path: /prometheus
      interval: 30s
