apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
