apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-configmap
  labels:
    app: promtail
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-service:3100/loki/api/v1/push

    scrape_configs:
      - job_name: terraform-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: terraform
              __path__: /var/log/jenkins/terraform-*.log
