apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'express-backend'
        static_configs:
          - targets: ['express-api:5000']
      - job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

